### ISSUE TITLE
Adapt to v1 contract interface and aggregate data

### ISSUE THREAD

**Issue by shanejearley** [consensusnetworks/casimir#295]
Referencing v1 interface output from #294 when merged. This will mostly affect fetching and displaying user stake and rewards (or just increasing stake, for compounding). Some fetching and computation will be moved in #256 so it will be worth coordinating with @hawyar when we get to that point. But, you will at least hand the same interface to @DemogorGod regardless of underlying implementation.

**Comment by ccali11** [comment]
Using this space to think out loud a bit (will edit to update ad hoc):

- Need an aggregator method to iterate over user accounts and check amount staked, where, and amount of rewards at each validator

**Comment by ccali11** [comment]
@shanejearley - Going to PR this now but left some specific implementation around rewards calculation out until we decide on what we want calculated where. Definitely down to do that in a separate PR (once we decide what we want to fetch/subscribe/listen to and where (FE vs BE)). Gained decent understanding of how to interface with SSVManager, which will allow me to more rapidly develop next related features, so that's a win imho.
